version: '3.3'

services:
  minecraft-server:
    ports:
      - "25565:25565"

    environment:
      EULA: "TRUE"
      DIFFICULTY: "normal"

    image: itzg/minecraft-server

    container_name: mc

    tty: true
    stdin_open: true
    restart: always
